# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020b347d59fab7f09d7869fa6e4d136a315fc2c447f19029089fc241237a858062f3f6584ecf6b210e4ae79f60cdb62b9cdbcf23df332b95625671bfa5f5312a

test:
  secret_key_base: 6d241b27a60054013f777c93309478a1aaa847f423b5c935f23d100e536428c30ddd4774c5756baa61b5dd2cb46655d87d0abd43e939c4a322dccfab3e8dc1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
